user-agent:
  items:
    - Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_8; en-us) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50
    - Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0;
    - Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0)
    - Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0)
    - Mozilla/5.0 (Macintosh; Intel Mac OS X 10.6; rv:2.0.1) Gecko/20100101 Firefox/4.0.1
    - Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; en) Presto/2.8.131 Version/11.11
    - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.163 Safari/535.1
    - Mozilla/5.0 (Windows NT 6.1; WOW64; rv:6.0) Gecko/20100101 Firefox/6.0
    - Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.50 (KHTML, like Gecko) Version/5.1 Safari/534.50
    - Opera/9.80 (Windows NT 6.1; U; zh-cn) Presto/2.9.168 Version/11.50
    - Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 5.1; The World)

proxy:
  ip: https://www.kuaidaili.com/free/inha/

custom-analysis:
  mappers:
    - name: hello
      analysisClass: cn.edu.nju.candleflame.rss_spider.feed.FeedChanger
      frequency: 2

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spider?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update